
baseURL = 'https://theme-unclebike-xyz.pages.dev/'
languageCode = 'en-us'
title = 'Uncle Bike'
theme = 'braun-hugo'
outputs.home = [
	'HTML',
	'JSON',
]
markup.goldmark.renderer.unsafe = true
menu.main = [
	{ name = 'Home', url = '/', weight = 1.0 },
	{ name = 'Services', url = '/services/', weight = 2.0 },
	{ name = 'Membership', url = '/membership/', weight = 3.0 },
	{ name = 'About', url = '/about/', weight = 4.0 },
	{ name = 'Contact', url = '/contact/', weight = 5.0 },
	{ name = 'News', url = '/posts/', weight = 6.0 },
]
imaging.quality = 75.0
imaging.resampleFilter = 'lanczos'
related.threshold = 80.0
related.includeNewer = true
related.indices = [
	{ name = 'tags', weight = 100.0 },
]
taxonomies.tag = 'tags'
taxonomies.author = 'authors'
permalinks.pages = '/:filename/'
params.description = 'Uncle Bike'
params.author = 'Braun'
params.edit_mode = false
params.color_combinations = 'Default'
params.appearance = 'system'
params.tagline_text = 'Designer and creator.'
params.show_navigation_icons = true
params.navigation_buttons = 'Subscription'
params.navigation_buttons_text = 'Action'
params.navigation_buttons_link = 'https://themex.studio'
params.hero_layout = 'Rectangle image top'
params.case_study_card_style = 'Full row'
params.blog_article_layout = 'Card'
params.blog_image_orientation = 'Landscape'
params.excluded_tags = 'books,now,hash-timeline,hash-gallery'
params.email_signup_text = 'Subscribe to my monthly newsletter'
params.show_author = false
params.show_social_share = false
params.show_subscription_box = false
params.posts_per_page = 18.0
