name = "zenbooker-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "src/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
CF_ACCESS_TEAM_DOMAIN = "unclebike"

[[d1_databases]]
binding = "DB"
database_name = "zenbooker"
database_id = "7e36e0fb-dc2a-4f02-a6ac-1b292927d8a0"
migrations_dir = "../migrations"

[triggers]
crons = ["0 13 * * *"]
